owner: seven-retail
repo: uptime-monitor

sites:
  - name: "Golden Hotpot & Grill's Promotion Website"
    url: $SITE_URL_GHG_PROMOTION
    expectedStatusCodes:
      - 404
  - name: "Golden Lamian's Promotion Website"
    url: $SITE_URL_GL_PROMOTION
    expectedStatusCodes:
      - 404
  - name: "Seven Retail's API"
    url: $SITE_URL_API
  - name: "Seven Retail's Content Management System"
    url: $SITE_URL_CMS
    expectedStatusCodes:
      - 401

status-website:
  cname: uptime.seven-retail.com
  name: "Seven Retail's uptime monitor"
  theme: night
  logoUrl: https://raw.githubusercontent.com/seven-retail/uptime-monitor/master/assets/logo.avif
  introTitle: "**Seven Retail**'s uptime monitor"
  introMessage: This is a status page which uses **real-time** data from our [GitHub repository](https://github.com/seven-retail/uptime-monitor).
  navbar:
    - title: Status
      href: /

i18n:
  footer: This page is [open source]($REPO), powered by [Upptime](https://upptime.js.org)
